spring:
  application:
    name: aggregated-data-service

server:
  port: 8002
  error:
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true