spring:
    application:
        name: employee-service
    datasource:
        url: jdbc:h2:mem:employeedb
        driverClassName: org.h2.Driver
        username: admin
        password: ${dbPassword}
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true

server:
    port: 8001

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        enabled: true
        register-with-eureka: true
        fetch-registry: true
    instance:
        prefer-ip-address: true